spring:
  application:
    name: PayedIn

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc:
          batch_size: 200
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payedin
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:11111111}